### ISSUE TITLE
How to handle variants?

### ISSUE THREAD

**Issue by deantheiceman** [appstract/laravel-stock#7]
I'm creating an application which uses variants, what would be the suggested way to handle stock of main product and variants using your package?

For example if I used a table layout like this

products
products_variants
products_variants_options

Where variants are like size and color

variants options are small, medium, large and blue, red, white

Thanks

**Comment by gizburdt** [comment]
I think you should `use HasStock` on a product variation, because this is the model you want to track stock on.
Maybe write your own function on the Product model to calculate full stock of all variations together.

**Comment by deantheiceman** [comment]
Thanks for your advice.

Last quesiton, any ideas if this could potentially handle something like warehouses? 

is in stock at which warehouse
